// Generated by CoffeeScript 1.7.1
(function() {
  var canvasEdgeX, canvasEdgeY, setSizes;

  canvasEdgeX = $(window).width();

  canvasEdgeY = $(window).height();

  setSizes = function() {
    canvasEdgeX = $(window).width();
    canvasEdgeY = $(window).height();
    canvas.width = canvasEdgeX;
    return canvas.height = canvasEdgeY;
  };

  jQuery(function() {
    var canvas;
    canvas = document.getElementById("canvas");
    return setSizes();
  });

}).call(this);
