// Generated by CoffeeScript 1.7.1
var FRAMERATE, INTERVAL, addMenus, draw, endGame, game, gameLoop, generateTerrain, imgBase, menuCode, removeMenus, runLevel, setSizes, startLoop, toGrid;

FRAMERATE = 1;

INTERVAL = 1000 / FRAMERATE;

game = new Object({
  loopCounter: 0,
  currentLevel: 0,
  over: false
});

imgBase = new Image({
  src: "images/icon_18231.svg",
  height: 50,
  width: 50
});

menuCode = "<div id='startMenu'> <p>Hello game, this is game.</p> <a href='#' class='menuLinkOne'>Start level one.</a> </div>";

removeMenus = function() {
  console.log("removeMenus runs");
  if ($("#startMenu").length === 0) {
    console.log("removeMenus warning: no #startMenu to remove");
  }
  if ($("#startMenu").length > 0) {
    return $("#startMenu").remove();
  }
};

addMenus = function() {
  console.log("addMenus runs");
  if ($("#startMenu").length > 0) {
    console.log("removeMenus warning: #startMenu already exists");
  }
  if ($("#startMenu").length === 0) {
    $('#menu').append(function() {
      return menuCode;
    });
    return $('.menuLinkOne').on('click', function() {
      return runLevel(100);
    });
  }
};

setSizes = function() {
  console.log("setSizes runs");
  canvas.width = $(window).width();
  return canvas.height = $(window).height();
};

startLoop = function() {
  console.log("startLoop runs");
  return setInterval(gameLoop, INTERVAL);
};

endGame = function() {
  console.log("endGame runs");
  return addMenus();
};

runLevel = function(levelName) {
  console.log("runLevel runs level:", levelName);
  game.currentLevel = levelName;
  game.loopCounter = 0;
  console.log("runLevel sets gameLoopCounter to", game.loopCounter);
  game.canvas = document.getElementById("canvas");
  console.log("runLevel creates new game.canvas:", game.canvas);
  setSizes();
  removeMenus();
  generateTerrain();
  if (game.over === false) {
    startLoop();
  }
  return game.over = false;
};

gameLoop = function() {
  if (game.currentLevel === 100 && game.over === false) {
    console.log("level 100 bizness logics, yo");
  }
  if (game.over === false) {
    game.loopCounter += 1;
    console.log("gameLoop is active");
    console.log("game.loopCounter =", game.loopCounter);
    draw();
    if (game.loopCounter >= 3) {
      game.over = true;
    }
    if (game.over === true) {
      return endGame();
    }
  }
};

draw = function() {
  var centerX, centerY;
  console.log("draw runs");
  centerX = toGrid(game.canvas.width / 2);
  return centerY = toGrid(game.canvas.height / 2);
};

toGrid = function(number) {
  return Math.floor(number / 50) * 50;
};

generateTerrain = function() {
  console.log("generateTerrain runs");
  return console.log("generateTerrain error: empty function");
};

jQuery(function() {
  console.log("$ document ready");
  setSizes();
  return addMenus();
});

console.log("testing: grid()");

console.log(toGrid(0) === 0);

console.log(toGrid(1) === 0);

console.log(toGrid(50) === 50);

console.log(toGrid(51) === 50);

console.log(toGrid(999999999999999) === 999999999999950);

console.log(toGrid(-1) === -50);

console.log(toGrid(-51) === -100);
